//! [`Genotype`] implementations for all texture configuration types.
//!
//! Each config struct implements [`symbios_genetics::Genotype`], making it
//! compatible with `SimpleGA`, `Nsga2`, and `MapElites` from that crate.
//!
//! # Mutation
//! Each numeric field is perturbed independently with probability `rate`.
//! Floating-point fields receive a uniform perturbation scaled to the field's
//! natural range.  Integer fields step by ±1.  Boolean fields are flipped.
//! Seed fields are replaced entirely.
//!
//! # Crossover
//! Uniform field crossover: each field is drawn independently from one of the
//! two parents at random (50/50).  Color channels are crossed over per-channel
//! for finer-grained colour mixing.
//!
//! # Where the fields come from
//! Every impl in this module is generated by `impl_genotype!` as a callback
//! over [`for_each_texture_field!`](crate::for_each_texture_field) — the one
//! per-field table. This module owns the *semantics* of each field kind (the
//! arms below) and nothing about any individual field: a range lives in the
//! registry, beside the same range the editor and an application's record
//! sanitiser use.
//!
//! The order of a config's rows in that table is the order `mutate` draws
//! from the RNG, so it is behaviour rather than presentation, and
//! `tests/genotype_behaviour.rs` pins it.

use rand::Rng;
use symbios_genetics::Genotype;

use crate::{brick::BrickConfig, shingle::ShingleConfig};
// --- shared helpers ---------------------------------------------------------

/// Perturb a `f64` by a uniform step in `(-half_range, +half_range)` with
/// probability `rate`, clamped to `[min, max]`.
#[inline]
fn mutate_f64<R: Rng>(
    val: f64,
    rng: &mut R,
    rate: f32,
    half_range: f64,
    min: f64,
    max: f64,
) -> f64 {
    if rng.random::<f32>() < rate {
        (val + (rng.random::<f64>() - 0.5) * 2.0 * half_range).clamp(min, max)
    } else {
        val
    }
}

/// Perturb a `f32` by a uniform step in `(-half_range, +half_range)` with
/// probability `rate`, clamped to `[min, max]`.
#[inline]
fn mutate_f32<R: Rng>(
    val: f32,
    rng: &mut R,
    rate: f32,
    half_range: f32,
    min: f32,
    max: f32,
) -> f32 {
    if rng.random::<f32>() < rate {
        (val + (rng.random::<f32>() - 0.5) * 2.0 * half_range).clamp(min, max)
    } else {
        val
    }
}

/// Perturb a `usize` by ±1 with probability `rate`, clamped to `[min, max]`.
#[inline]
fn mutate_usize<R: Rng>(val: usize, rng: &mut R, rate: f32, min: usize, max: usize) -> usize {
    if rng.random::<f32>() < rate {
        if rng.random::<bool>() {
            val.saturating_add(1).min(max)
        } else {
            val.saturating_sub(1).max(min)
        }
    } else {
        val
    }
}

/// Replace a `u32` seed entirely with probability `rate`.
#[inline]
fn mutate_seed<R: Rng>(val: u32, rng: &mut R, rate: f32) -> u32 {
    if rng.random::<f32>() < rate {
        rng.random::<u32>()
    } else {
        val
    }
}

/// Mutate each channel of an RGB `[f32; 3]` colour independently.
#[inline]
fn mutate_color3<R: Rng>(color: [f32; 3], rng: &mut R, rate: f32, half_range: f32) -> [f32; 3] {
    [
        mutate_f32(color[0], rng, rate, half_range, 0.0, 1.0),
        mutate_f32(color[1], rng, rate, half_range, 0.0, 1.0),
        mutate_f32(color[2], rng, rate, half_range, 0.0, 1.0),
    ]
}

/// Crossover two RGB colours channel-by-channel.
#[inline]
fn crossover_color3<R: Rng>(a: [f32; 3], b: [f32; 3], rng: &mut R) -> [f32; 3] {
    [
        if rng.random::<bool>() { a[0] } else { b[0] },
        if rng.random::<bool>() { a[1] } else { b[1] },
        if rng.random::<bool>() { a[2] } else { b[2] },
    ]
}

// --- coupled-field fixups ---------------------------------------------------

// Two configs carry an invariant that couples two fields, which no per-field
// row can express. They run after the per-field pass on both `mutate` and
// `crossover`; the registry names them with `fixup`.

/// Snap `row_offset` so `scale * row_offset` is an integer — required for a
/// brick bond to tile vertically.
fn snap_row_offset(cfg: &mut BrickConfig) {
    cfg.snap_row_offset();
}

/// Snap `stagger` so `scale * stagger` is an integer — the same tiling
/// invariant for shingle courses.
fn snap_stagger(cfg: &mut ShingleConfig) {
    if cfg.scale > 0.0 {
        cfg.stagger = (cfg.scale * cfg.stagger).round() / cfg.scale;
    }
}

// --- declarative macro ------------------------------------------------------

/// Generates `Genotype` (mutate + crossover) for every config in
/// [`for_each_texture_field!`](crate::for_each_texture_field).
///
/// The registry's row kinds map to mutation and crossover as follows; the UI
/// columns (`label`, the editor function, the panel salt) and the whole
/// `layout` list are matched as opaque tokens and discarded.
///
/// | Kind | Mutation | Crossover |
/// |------|----------|-----------|
/// | `seed` | Replace with random `u32` | 50/50 pick |
/// | `f64` | Uniform perturbation, clamp to the envelope | 50/50 pick |
/// | `f64_round` | Perturbation + `.round()` | 50/50 pick |
/// | `f32` | Uniform perturbation, clamp to the envelope | 50/50 pick |
/// | `usize` | ±1 step, clamp to the envelope | 50/50 pick |
/// | `color3` | Per-channel f32 perturbation | Per-channel 50/50 |
/// | `bool` | Flip with probability `rate` | 50/50 pick |
/// | `enum_pick` | Cycle to next variant | 50/50 pick (clone) |
/// | `nested` | Delegate to nested `Genotype` | Delegate to nested crossover |
macro_rules! impl_genotype {
    // Callback entry: one impl per registry entry.
    (
        $(
            $Config:ty, $header:literal, $editor:ident
            $(, fixup $fixup:ident )?
            { $(
                $kind:ident ( $field:ident $($rest:tt)* )
                $( explore ( $xlo:expr, $xhi:expr ) )?
            ),+ $(,)? }
            $( layout { $($layout:tt)* } )?
        ),+ $(,)?
    ) => {
        $(
            impl Genotype for $Config {
                fn mutate<R: Rng>(&mut self, rng: &mut R, rate: f32) {
                    $( impl_genotype!(
                        @mutate self, rng, rate,
                        $kind ($field $($rest)*) $( explore($xlo, $xhi) )?
                    ); )+
                    $( $fixup(self); )?
                }

                fn crossover<R: Rng>(&self, other: &Self, rng: &mut R) -> Self {
                    #[allow(unused_mut)]
                    let mut child = Self {
                        $( $field: impl_genotype!(
                            @crossover self, other, rng, $kind ($field $($rest)*)
                        ), )+
                    };
                    $( $fixup(&mut child); )?
                    child
                }
            }
        )+
    };

    // --- mutate arms --------------------------------------------------------

    (@mutate $s:ident, $rng:ident, $rate:ident, seed ($f:ident, $label:tt)) => {
        $s.$f = mutate_seed($s.$f, $rng, $rate);
    };
    (@mutate $s:ident, $rng:ident, $rate:ident,
     f64 ($f:ident, $label:tt, $min:expr, $max:expr, $half:expr)) => {
        $s.$f = mutate_f64($s.$f, $rng, $rate, $half, $min, $max);
    };
    (@mutate $s:ident, $rng:ident, $rate:ident,
     f64 ($f:ident, $label:tt, $min:expr, $max:expr, $half:expr)
     explore ($xlo:expr, $xhi:expr)) => {
        $s.$f = mutate_f64($s.$f, $rng, $rate, $half, $xlo, $xhi);
    };
    (@mutate $s:ident, $rng:ident, $rate:ident,
     f64_round ($f:ident, $label:tt, $min:expr, $max:expr, $half:expr)) => {
        $s.$f = mutate_f64($s.$f, $rng, $rate, $half, $min, $max).round();
    };
    (@mutate $s:ident, $rng:ident, $rate:ident,
     f64_round ($f:ident, $label:tt, $min:expr, $max:expr, $half:expr)
     explore ($xlo:expr, $xhi:expr)) => {
        $s.$f = mutate_f64($s.$f, $rng, $rate, $half, $xlo, $xhi).round();
    };
    (@mutate $s:ident, $rng:ident, $rate:ident,
     f32 ($f:ident, $label:tt, $min:expr, $max:expr, $half:expr)) => {
        $s.$f = mutate_f32($s.$f, $rng, $rate, $half, $min, $max);
    };
    (@mutate $s:ident, $rng:ident, $rate:ident,
     f32 ($f:ident, $label:tt, $min:expr, $max:expr, $half:expr)
     explore ($xlo:expr, $xhi:expr)) => {
        $s.$f = mutate_f32($s.$f, $rng, $rate, $half, $xlo, $xhi);
    };
    (@mutate $s:ident, $rng:ident, $rate:ident,
     usize ($f:ident, $label:tt, $min:expr, $max:expr)) => {
        $s.$f = mutate_usize($s.$f, $rng, $rate, $min, $max);
    };
    (@mutate $s:ident, $rng:ident, $rate:ident,
     usize ($f:ident, $label:tt, $min:expr, $max:expr)
     explore ($xlo:expr, $xhi:expr)) => {
        $s.$f = mutate_usize($s.$f, $rng, $rate, $xlo, $xhi);
    };
    (@mutate $s:ident, $rng:ident, $rate:ident, color3 ($f:ident, $label:tt, $half:expr)) => {
        $s.$f = mutate_color3($s.$f, $rng, $rate, $half);
    };
    (@mutate $s:ident, $rng:ident, $rate:ident, bool ($f:ident, $label:tt)) => {
        if $rng.random::<f32>() < $rate { $s.$f = !$s.$f; }
    };
    (@mutate $s:ident, $rng:ident, $rate:ident,
     enum_pick ($f:ident, $label:tt, [ $(($variant:expr, $btn:literal)),+ ])) => {
        if $rng.random::<f32>() < $rate {
            let variants = [ $($variant),+ ];
            let cur = variants.iter().position(|v| *v == $s.$f).unwrap_or(0);
            $s.$f = variants[(cur + 1) % variants.len()].clone();
        }
    };
    (@mutate $s:ident, $rng:ident, $rate:ident,
     nested ($f:ident, $sub:ty, $editor:ident, $salt:literal)) => {
        $s.$f.mutate($rng, $rate);
    };

    // --- crossover arms -----------------------------------------------------

    (@crossover $a:ident, $b:ident, $rng:ident, color3 ($f:ident $($rest:tt)*)) => {
        crossover_color3($a.$f, $b.$f, $rng)
    };
    (@crossover $a:ident, $b:ident, $rng:ident, enum_pick ($f:ident $($rest:tt)*)) => {
        if $rng.random::<bool>() { $a.$f.clone() } else { $b.$f.clone() }
    };
    (@crossover $a:ident, $b:ident, $rng:ident, nested ($f:ident $($rest:tt)*)) => {
        $a.$f.crossover(&$b.$f, $rng)
    };
    // Every other kind is a plain 50/50 pick of a `Copy` scalar.
    (@crossover $a:ident, $b:ident, $rng:ident, $kind:ident ($f:ident $($rest:tt)*)) => {
        if $rng.random::<bool>() { $a.$f } else { $b.$f }
    };
}

// ---------------------------------------------------------------------------
// Implementations — one per row of the per-field registry
// ---------------------------------------------------------------------------

crate::for_each_texture_field!(impl_genotype);
// The `impl Genotype for TextureConfig` dispatch lives in the
// `bevy_symbios_texture` wrapper crate alongside the `TextureConfig` enum
// definition (the enum's inherent `spawn`/`render_properties` methods are
// Bevy-coupled, so it cannot live here in the Bevy-free core).

// --- tests ------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use rand::SeedableRng;

    use super::*;
    use crate::{
        bark::BarkConfig, ground::GroundConfig, leaf::LeafConfig, rock::RockConfig,
        twig::TwigConfig,
    };

    fn seeded_rng() -> rand::rngs::StdRng {
        rand::rngs::StdRng::seed_from_u64(42)
    }

    #[test]
    fn bark_mutate_is_deterministic() {
        let base = BarkConfig::default();
        let mut a = base.clone();
        let mut b = base.clone();
        a.mutate(&mut seeded_rng(), 1.0);
        b.mutate(&mut seeded_rng(), 1.0);
        // Same seed → same result.
        assert_eq!(a.seed, b.seed);
        assert_eq!(a.octaves, b.octaves);
    }

    #[test]
    fn bark_mutate_rate_zero_is_identity() {
        let base = BarkConfig::default();
        let mut c = base.clone();
        c.mutate(&mut seeded_rng(), 0.0);
        assert_eq!(c.seed, base.seed);
        assert_eq!(c.octaves, base.octaves);
        assert!((c.scale - base.scale).abs() < f64::EPSILON);
    }

    #[test]
    fn bark_crossover_fields_from_parents() {
        let a = BarkConfig::default();
        let b = BarkConfig {
            seed: 99,
            octaves: 3,
            scale: 8.0,
            ..BarkConfig::default()
        };
        let child = a.crossover(&b, &mut seeded_rng());
        // Every field must come from one of the two parents.
        assert!(child.seed == a.seed || child.seed == b.seed);
        assert!(child.octaves == a.octaves || child.octaves == b.octaves);
        assert!(child.scale == a.scale || child.scale == b.scale);
    }

    #[test]
    fn rock_mutate_rate_zero_is_identity() {
        let base = RockConfig::default();
        let mut c = base.clone();
        c.mutate(&mut seeded_rng(), 0.0);
        assert_eq!(c.seed, base.seed);
        assert!((c.attenuation - base.attenuation).abs() < f64::EPSILON);
    }

    #[test]
    fn ground_mutate_clamps_micro_weight() {
        let mut c = GroundConfig {
            micro_weight: 0.99,
            ..GroundConfig::default()
        };
        // Mutate with rate=1.0 many times — micro_weight must stay in [0, 1].
        let mut rng = seeded_rng();
        for _ in 0..50 {
            c.mutate(&mut rng, 1.0);
            assert!((0.0..=1.0).contains(&c.micro_weight));
        }
    }

    #[test]
    fn leaf_crossover_valid() {
        let a = LeafConfig::default();
        let b = LeafConfig {
            seed: 77,
            vein_angle: 4.0,
            ..LeafConfig::default()
        };
        let child = a.crossover(&b, &mut seeded_rng());
        assert!(child.seed == a.seed || child.seed == b.seed);
        assert!(child.vein_angle == a.vein_angle || child.vein_angle == b.vein_angle);
    }

    #[test]
    fn twig_mutate_delegates_to_leaf() {
        let base = TwigConfig::default();
        let mut c = base.clone();
        // Rate = 1.0 always mutates — leaf seed must change from default (rarely stays same).
        // We just check it doesn't panic and leaf_pairs stays in range.
        c.mutate(&mut seeded_rng(), 1.0);
        assert!((1..=8).contains(&c.leaf_pairs));
        assert!(c.stem_half_width >= 0.005 && c.stem_half_width <= 0.05);
    }

    #[test]
    fn twig_crossover_valid() {
        let a = TwigConfig {
            sympodial: false,
            leaf_pairs: 2,
            ..TwigConfig::default()
        };
        let b = TwigConfig {
            sympodial: true,
            leaf_pairs: 6,
            ..TwigConfig::default()
        };
        let child = a.crossover(&b, &mut seeded_rng());
        assert!(child.leaf_pairs == a.leaf_pairs || child.leaf_pairs == b.leaf_pairs);
        assert!(child.sympodial == a.sympodial || child.sympodial == b.sympodial);
    }
}
